### PR TITLE
Checking that links have titles of locator text.

### PR DESCRIPTION
**Pull request by kevbite**
Connects #157 

Just adding in a or has title attribute for `<a...` tags.

### CODE REVIEW

**Comment by adiel** [comment]
Looks good! Any chance you could have a go adding a test for this too?

**Comment by kevbite** [comment]
Sure thing, I'll try take a look at this today 👍

**Comment by kevbite** [comment]
I've updated with a simple acceptance test.

**Comment by adiel** [comment]
Thanks, looks good!

**Comment by Jetski5822** [comment]
Nice thanks

**Pull request merged**
