### PR TITLE
Nunit3

### PR DESCRIPTION
**Pull request by Blundell89**
Issue #142. Any comments/feedback then let me know :smile: 

Thanks

### CODE REVIEW

**Comment by abulhasanlakhani** [comment]
Any plans on this? I cannot update my projects just because of this. Kindly merge this pull request and update the nuget package. Thanks a lot

**Comment by adiel** [comment]
As I said on #142 I think it's the right approach, but I have not had time to review it yet. I have been moving house so it's not been an easy few weeks to find time for this. @abulhasanlakhani fancy taking some time to look through the code / run the tests and adding some feedback? I at least wanted to look at why 8 tests have been ignored before just merging it in.

**Comment by adiel** [comment]
Sorry man :( I forgot about you.

Assuming you are using your own fork now, you wanna talk about maybe maintaining the project going forward, PRs, nuget etc? I'm just not using windows day to day and so it's not practical for me really. If you are using it day to day, you are in a better position than me to review PRs etc.

**Comment by Blundell89** [comment]
Hey @adiel. No problem :smile: 

We'd definitely be interested in taking the project on. We've had some ideas about how we could extend it too so would be a good challenge!

Thanks

**Comment by adiel** [comment]
Cool, I'll get you added to the repo and nuget for starters.

**Comment by Blundell89** [comment]
Thanks buddy. I've accepted the repo invitation and created a personal account on nuget - my username is `blunny`.

**Comment by adiel** [comment]
You should subscribe here too: https://groups.google.com/d/forum/coypu

**Comment by pmcevoy** [comment]
Now that this is closed, I wonder if you propose to publish an updated nupkg for this support?  Coypu.Nunit forces a < 3.0 dependency on Nunit

**Comment by adiel** [comment]
@Blundell89 You gonna take a pass at this?

**Comment by Blundell89** [comment]
@adiel @pmcevoy Hey, yeah hoping to get it out soon but really want to get the broken tests fixed before pushing it. I'll keep you both updated :smile: 

Going to get some issues raised soon too with some ideas for taking the project forward

**Comment by mirhagk** [comment]
Hey we're also looking at this. We actually did the same kind of fix on our own copy, but it'd be good to have an official fix (right now we've just embedded the matchers within our test project itself, definitely not ideal). 

I got a bit of experience with nuget stuff and working with coypu now lol, so if you would like any help with this let me know.

**Comment by adiel** [comment]
@Blundell89 Been asked a couple more times to get this in. Can we get the changes from https://github.com/LiberisLabs/coypu over? You wanna make another PR?

**Pull request closed without merging**
