### PR TITLE
Upgrade c#, selenium, get working on macOS

### PR DESCRIPTION
**Pull request by adiel**
This builds on https://github.com/featurist/coypu/pull/225 to get the project building and tests running on my Mac.

Tests are mostly passing, but I have a 13 of test failures I don't totally understand as not ran this project in a while, not sure they are related to this change, or if they pass/fail in master on Windows currently.

@sbowler you wanna pick this up and see what more work you think it needs?

### CODE REVIEW

**Comment by sbowler** [comment]
I started looking at this, but have 20 test failures with a couple minor changes so I'm also not sure yet if the test failures are perhaps due to selenium updating as legit breakages or just a system set up issue or something of that sort. I'll try to look at this as soon as I can again.

**Comment by sbowler** [comment]
So I ran the tests on the current master branch and only had 11 failures so I'll probably want to check out the differences and see what may be going on.

**Comment by sbowler** [comment]
It seemed like most of the issue I had were likely caused by SSL issues. It would be nice if the unit testing had a good way to create the browser sessions ignoring insecure certificates. As it was that seemed fairly difficult to do. I pushed up the fixes for the test I felt were most truly needed. I think things are mostly good as best I can tell and the updates are desperately needed so I'll go ahead and merge this. However, I don't have Nuget.org permissions to be able to push out a release.

**Comment by adiel** [comment]
What's your nuget username, I'll add you

**Comment by sbowler** [comment]
I believe it should be bean56

**Comment by adiel** [comment]
There you go

**Comment by sbowler** [comment]
Do you want to add me to Coypu.NUnit as well?

**Pull request merged**
