### PR TITLE
Added possibility to pass arguments down to the browser when executing JavaScript scripts

### PR DESCRIPTION
**Pull request by drauch**
See feature request #128 .

### CODE REVIEW

**Comment by drauch** [comment]
Review points for you:
* Could `argAsElement.Native` be a problem and introduce stale element exceptions? If yes, please insert the correct retry logic, I'm not entirely sure how to do that the proper way.
* WatiNDriver throws a NotSupportedException so far, as I haven't found any possibility to pass down arguments.
* FakeDriver ignores the args so far (I think that is okay for now)

**Comment by adiel** [comment]
* Could argAsElement.Native be a problem and introduce stale element exceptions? If yes, please insert the correct retry logic, I'm not entirely sure how to do that the proper way.

That's fine. The design is that the Driver knows nothing of retry so stale element exceptions thrown here will be handled by the retry code further up.

* WatiNDriver throws a NotSupportedException so far, as I haven't found any possibility to pass down arguments.

That's also fine.

* FakeDriver ignores the args so far (I think that is okay for now)

That's ok, the main thing is that we add one acceptance test that actually calls BrowserWindow.ExecuteScript() with the extra argument(s).

Could you look at the test: ApiExamples.ExecuteScript_example and make one that uses the new arg? Would be more or less the same as your Driver test, just at the very outside of the API?

Cheers for this!

**Comment by drauch** [comment]
Done as well. See method `ExecuteScriptWithArgs_example`.

**Comment by adiel** [comment]
Cheers! Will pull, run tests and get it out later today hopefully.

**Pull request merged**
